name: CI

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v2

      - name: Uses NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      
      - run: npm ci # Similar command to npm install, except it's meant to be used in automated environments

      - run: npm run format:check

      - run: npm test -- --coverage
        env:
          CI: true